server:
  port: 8080

spring:
  application:
    name: serviceOne
  kafka:
    streams:
      properties:
        default:
          key:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          value:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  zipkin:
    baseUrl: "http://localhost:9411/"
    sender:
      type: "web"
  sleuth:
    sampler:
      probability: "1.0"
    web:
      skipPattern: (^cleanup.*)
    propagation-keys:
      - messageid
    log:
      slf4j:
        whitelisted-mdc-keys:
          - messageid
